before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: k1/QO5dIG4ZT9HOVK8xw/RFHMXqYvdNl64s9Sin126cO/hEBYpq2QO6tI15FnToJncFC+8L7a8x7zcTQ1a6XmzJ+0l9AAKz4mkeW3cvSiig3FK3MiTnjR5zvcI7+Jb1hgZqb9Ia1aI0TfS4Lp7LjttgOiilonHomUtx7fOA01ptPId6Sa/KTVkjjpxVg/X+9swXmzhPN2J58Q1wa6IbqEUz2jldPQVIWKG8AzxTcXDPLWSpvfyC5y1ndmPg6RW5lHn1d0T+JjmysLLHH8MC0n2W5A8dkOcVbyqitrtEc7s2gXv5s8Fp4fN7R74rEz9aSjKsDTF1iRgpGk82PTu3LmMXN9AyeHmuh79s/Y3OaU9N3CUg2+54jW+AEiv+dvWoT5Ngv6ul7eTS5b0K+tnZUx5Q7lLyfm03G/FImYeu+owpyjZ/kwKgovn58+Zp06kgZtzsUcSGwbIXpZ10raLftD4afBmfQ/X0idkjAXhTXSLeRVrsCmYGwWaA0iXobqwL4YYSAVb0jMs+0/ehTCoviHfLJc+BMsq2hLDvN2M6orpGOBuzFfS7r+imv6j+/tqTI+oU6BxfVID1EMVKk98KuPGLdTQnpXoABSLI/irK8Ar2WD9cdJX+WTw39IRY/VcrtbRX/Dnmrt5rW+AyIPcfODkR6qSDMuu3kMz25NE+x8pQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
